name: flutter_secure_storage
description: Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based solution is used in Android.
version: 3.3.1+1
author: German Saprykin <saprykin.h@gmail.com>
homepage: https://github.com/mogol/flutter_secure_storage

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterSecureStoragePlugin
      macos:
        pluginClass: FlutterSecureStoragePlugin
      android:
        package: com.it_nomads.fluttersecurestorage
        pluginClass: FlutterSecureStoragePlugin

dependencies:
  meta: "^1.1.2"
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.1.0 <3.0.0"
