name: flutter_secure_storage
description: Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based solution is used in Android.
version: 3.3.4
homepage: https://github.com/mogol/flutter_secure_storage

flutter:
  plugin:
    platforms:
      android:
        package: com.it_nomads.fluttersecurestorage
        pluginClass: FlutterSecureStoragePlugin
      ios:
        pluginClass: FlutterSecureStoragePlugin

dependencies:
  meta: "^1.1.2"
  flutter:
    sdk: flutter

environment:
    sdk: ">=1.19.0 <3.0.0"
