name: flutter_secure_storage
description: Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based solution is used in Android.
version: 4.2.1
homepage: https://github.com/mogol/flutter_secure_storage

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.26.0-17.6.pre'

flutter:
  plugin:
    platforms:
      android:
        package: com.it_nomads.fluttersecurestorage
        pluginClass: FlutterSecureStoragePlugin
      ios:
        pluginClass: FlutterSecureStoragePlugin
      linux:
        pluginClass: FlutterSecureStoragePlugin

dependencies:
  meta: '^1.3.0'
  flutter:
    sdk: flutter
